allowBuilds:
  esbuild: true
enablePrePostScripts: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@apimatic/*'
blockExoticSubdeps: true
overrides:
  '@types/node': '25.5.0'
  'browserslist': '4.23.3'
