/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of BadRequestResponseSdk
 */
interface BadRequestResponseSdk {
  /** Error message describing the bad request */
  message?: string;
  additionalProperties?: Record<string, unknown>;
}

export class BadRequestResponseSdkError extends ApiError<
  BadRequestResponseSdk
> {}
