/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, FileWrapper, RequestOptions } from '../core.js';
import {
  FeaturesToRemove,
  featuresToRemoveSchema,
} from '../models/featuresToRemove.js';
import { BaseController } from './baseController.js';
import { InternalServerErrorResponseError } from '../errors/internalServerErrorResponseError.js';
import { ProblemDetailsError } from '../errors/problemDetailsError.js';
import { UnauthorizedResponseError } from '../errors/unauthorizedResponseError.js';

export class ApiFeaturesController extends BaseController {
  /**
   * Strip specific features from an API by uploading the API specification file and the set of features
   * to strip. Currently, only OpenAPI 3.x specification files are supported for stripping. The features
   * that can be stripped include API Merging, Pagination, Webhooks, Callbacks, Multiple Auth Schemes,
   * OAuth2 and number of endpoints.
   *
   * @param file             The OpenAPI specification file to strip. Supported types: JSON,
   *                                                    YAML, or ZIP.
   * @param featuresToRemove Configuration for specifying which features to strip from API
   *                                                    Specification.
   * @return Response from the API call
   */
  async stripFeatures(
    file: FileWrapper,
    featuresToRemove: FeaturesToRemove,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('POST', '/api-features/strip');
    const mapped = req.prepareArgs({
      featuresToRemove: [featuresToRemove, featuresToRemoveSchema],
    });
    req.formData({ file: file, featuresToRemove: mapped.featuresToRemove });
    req.throwOn(400, ProblemDetailsError, 'Bad Request');
    req.throwOn(401, UnauthorizedResponseError, 'Unauthorized');
    req.throwOn(403, ProblemDetailsError, 'Subscription Issue');
    req.throwOn(500, InternalServerErrorResponseError, 'Internal Server Error');
    req.authenticate([{ authorization: true }]);
    return req.callAsStream(requestOptions);
  }
}
