/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, FileWrapper, RequestOptions } from '../core.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';
import { InternalServerErrorResponseError } from '../errors/internalServerErrorResponseError.js';
import { ProblemDetailsError } from '../errors/problemDetailsError.js';
import { UnauthorizedResponseError } from '../errors/unauthorizedResponseError.js';

export class ApiPruningController extends BaseController {
  /**
   * Prune specific features from an API by uploading the API specification file and the set of features
   * to prune. Currently, only OpenAPI 3.x specification files are supported for pruning. The features
   * that can be pruned include API Merging, Pagination, Webhooks, Callbacks, Multiple Auth Schemes,
   * OAuth2 and number of endpoints.
   *
   * You can also specify [API Metadata](https://docs.apimatic.io/manage-apis/apimatic-metadata) while
   * pruning the API using this endpoint. When specifying Metadata, the uploaded file will be a zip file
   * containing the API specification file and the `APIMATIC-META` json file.
   *
   * @param file               The OpenAPI 3.x specification file to prune (JSON or YAML).
   * @param restrictedFeatures A JSON-encoded object describing which features to prune.
   * @return Response from the API call
   */
  async pruneApi(
    file: FileWrapper,
    restrictedFeatures: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('POST', '/api/pruning/prune');
    const mapped = req.prepareArgs({
      restrictedFeatures: [restrictedFeatures, string()],
    });
    req.formData({ file: file, restrictedFeatures: mapped.restrictedFeatures });
    req.throwOn(400, ProblemDetailsError, 'Bad Request');
    req.throwOn(401, UnauthorizedResponseError, 'Unauthorized');
    req.throwOn(403, ProblemDetailsError, 'Subscription Issue');
    req.throwOn(500, InternalServerErrorResponseError, 'Internal Server Error');
    req.authenticate([{ authorization: true }]);
    return req.callAsStream(requestOptions);
  }
}
