/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, FileWrapper, RequestOptions } from '../core.js';
import { ContentType, contentTypeSchema } from '../models/contentType.js';
import { SdkLanguages, sdkLanguagesSchema } from '../models/sdkLanguages.js';
import { BaseController } from './baseController.js';
import { InternalServerErrorResponseError } from '../errors/internalServerErrorResponseError.js';
import { ProblemDetailsError } from '../errors/problemDetailsError.js';
import { UnauthorizedResponseError } from '../errors/unauthorizedResponseError.js';

export class V2SdkGenerationController extends BaseController {
  /**
   * Create a V2 SDK Generation request by providing a Build Input
   *
   * @param contentType
   * @param file         The input file to the SDK Generator. Must contain the build file or a spec
   *                                     folder containing the API Specification.
   * @param language     Languages for which SDKs can be generated.
   * @return Response from the API call
   */
  async generateV2SdkViaBuildInput(
    contentType: ContentType,
    file: FileWrapper,
    language: SdkLanguages,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('POST', '/sdk/v2');
    const mapped = req.prepareArgs({
      contentType: [contentType, contentTypeSchema],
      language: [language, sdkLanguagesSchema],
    });
    req.header('Content-Type', mapped.contentType);
    req.formData({ file: file, language: mapped.language });
    req.throwOn(400, ProblemDetailsError, 'Bad Request');
    req.throwOn(401, UnauthorizedResponseError, 'Unauthorized');
    req.throwOn(500, InternalServerErrorResponseError, 'Internal Server Error');
    req.authenticate([{ authorization: true }]);
    return req.callAsStream(requestOptions);
  }
}
