/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Accept4
 */
export enum Accept4 {
  EnumApplicationzip = 'application/zip',
}

/**
 * Schema for Accept4
 */
export const accept4Schema: Schema<Accept4> = stringEnum(Accept4);
