/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Accept1
 */
export enum Accept1 {
  EnumApplicationzip = 'application/zip',
}

/**
 * Schema for Accept1
 */
export const accept1Schema: Schema<Accept1> = stringEnum(Accept1);
