/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { CodeGeneration } from './codeGeneration';

/** The Code Generation structure encapsulates all the  the details of an SDK generation performed against an API Entity */
export interface APIEntityCodeGeneration extends CodeGeneration {
  /** Unique API Entity Identifier */
  apiEntityId: string;
}

export const aPIEntityCodeGenerationSchema: Schema<APIEntityCodeGeneration> = object(
  { apiEntityId: ['apiEntityId', string()] }
);
