/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { ApiEntity } from './apiEntity';
import { CustomType, customTypeSchema } from './customType';
import { Endpoint, endpointSchema } from './endpoint';

/** The structure collects API Endpoints and Custom Types to display detailed information on API Entity. */
export interface ApiEntityDetailed extends ApiEntity {
  /** API Endpoints */
  endpoints: Endpoint[];
  /** Complex Custom Model Types */
  customTypes: CustomType[];
}

export const apiEntityDetailedSchema: Schema<ApiEntityDetailed> = object({
  endpoints: ['endpoints', array(lazy(() => endpointSchema))],
  customTypes: ['customTypes', array(lazy(() => customTypeSchema))],
});
