/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CodeGenerationVersion
 */
export enum CodeGenerationVersion {
  V3 = 'v3',
  V4 = 'v4',
}

/**
 * Schema for CodeGenerationVersion
 */
export const codeGenerationVersionSchema: Schema<CodeGenerationVersion> = stringEnum(
  CodeGenerationVersion
);
