/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

/** This structure contains all details that goes into package deployment. */
export interface CSNETSTANDARDLIB {
  /** Unique package identifier */
  id?: string;
  /** Package Repository as per platform */
  packageRepository: string;
  /** Package Name */
  packageName: string;
  version: string;
  /** Any additional platform specific deployment detail */
  additionalDeploymentInformation?: unknown;
  /** Link of deployed package */
  link?: string;
}

export const cSNETSTANDARDLIBSchema: Schema<CSNETSTANDARDLIB> = object({
  id: ['id', optional(string())],
  packageRepository: ['packageRepository', string()],
  packageName: ['packageName', string()],
  version: ['version', string()],
  additionalDeploymentInformation: [
    'additionalDeploymentInformation',
    unknown(),
  ],
  link: ['link', optional(string())],
});
