/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExportFormats
 */
export enum ExportFormats {
  APIMATIC = 'APIMATIC',
  WADL2009 = 'WADL2009',
  WADL2006 = 'WADL2006',
  WSDL = 'WSDL',
  Swagger10 = 'Swagger10',
  Swagger20 = 'Swagger20',
  SwaggerYaml = 'SwaggerYaml',
  OpenApi3Json = 'OpenApi3Json',
  OpenApi3Yaml = 'OpenApi3Yaml',
  IODocs = 'IODocs',
  IODocsV0314 = 'IODocsV0314',
  APIBluePrint = 'APIBluePrint',
  RAML = 'RAML',
  RAML10 = 'RAML10',
  GoogleDiscovery = 'GoogleDiscovery',
  Mashape = 'Mashape',
  Postman10 = 'Postman10',
  Postman20 = 'Postman20',
  GraphQlSchema = 'GraphQlSchema',
}

/**
 * Schema for ExportFormats
 */
export const exportFormatsSchema: Schema<ExportFormats> = stringEnum(ExportFormats);
