/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema } from '../schema.js';
import {
  RemovableFeature,
  removableFeatureSchema,
} from './removableFeature.js';

/** Configuration for specifying which features to strip from API Specification. */
export interface FeaturesToRemove {
  /** List of feature names to strip. */
  features?: RemovableFeature[];
  /** Number of endpoints to keep. */
  endpointsToKeep?: number;
}

export const featuresToRemoveSchema: Schema<FeaturesToRemove> = object({
  features: ['features', optional(array(removableFeatureSchema))],
  endpointsToKeep: ['endpointsToKeep', optional(number())],
});
