/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** This structure contains details of importing a new API Version */
export interface ImportNewVersion {
  /** Version to be overridden */
  versionOverride: string;
  /** URL of new API Spec */
  url: string;
}

export const importNewVersionSchema: Schema<ImportNewVersion> = object({
  versionOverride: ['version_override', string()],
  url: ['url', string()],
});
