/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Contains a url field to allow Apis to be imported via url */
export interface InplaceImportApiEntityWithUrl {
  /** Url for Api to be imported */
  url: string;
}

export const inplaceImportApiEntityWithUrlSchema: Schema<InplaceImportApiEntityWithUrl> = object(
  { url: ['url', string()] }
);
