/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Server, serverSchema } from './server.js';

/** An environment consists of a set of servers with base URL values. The environment can be changed programatically allowing rapid switching between different environments. For example the user can specify a Production and Testing Environment and switch between them in the generated SDK. */
export interface MEnvironment {
  /** Unique Environment Identifier */
  id: string;
  /** Environment Name */
  name: string;
  /** The user can specify multiple servers within an environment. A server comprises of a name and a url. */
  servers: Server[];
  additionalProperties?: Record<string, unknown>;
}

export const mEnvironmentSchema: Schema<MEnvironment> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      name: ['name', string()],
      servers: ['servers', array(serverSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
