/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ApiValidationSummary,
  apiValidationSummarySchema,
} from './apiValidationSummary.js';
import {
  DocsValidationSummary,
  docsValidationSummarySchema,
} from './docsValidationSummary.js';
import {
  ImportValidationSummary,
  importValidationSummarySchema,
} from './importValidationSummary.js';

export interface MetaData {
  importValidationSummary: ImportValidationSummary;
  apiValidationSummary: ApiValidationSummary;
  docsValidationSummary: DocsValidationSummary;
  additionalProperties?: Record<string, unknown>;
}

export const metaDataSchema: Schema<MetaData> = lazy(() =>
  typedExpandoObject(
    {
      importValidationSummary: [
        'importValidationSummary',
        importValidationSummarySchema,
      ],
      apiValidationSummary: [
        'apiValidationSummary',
        apiValidationSummarySchema,
      ],
      docsValidationSummary: [
        'docsValidationSummary',
        docsValidationSummarySchema,
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
