/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { Field } from './field';

/** Parameters are options passed with the endpoint */
export interface Parameter extends Field {
  /** Specify Parameter Format */
  paramFormat: string;
}

export const parameterSchema: Schema<Parameter> = object({
  paramFormat: ['ParamFormat', string()],
});
