/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { ProblemDetails, problemDetailsSchema } from './problemDetails.js';
import { Status, statusSchema } from './status.js';

export interface PortalGenerationStatusResponse {
  status: Status;
  detail?: ProblemDetails;
}

export const portalGenerationStatusResponseSchema: Schema<PortalGenerationStatusResponse> = lazy(
  () =>
    object({
      status: ['status', statusSchema],
      detail: ['detail', optional(problemDetailsSchema)],
    })
);
