/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema.js';
import { Status, statusSchema } from './status.js';

export interface PortalGenerationStatusResponse {
  status: Status;
}

export const portalGenerationStatusResponseSchema: Schema<PortalGenerationStatusResponse> = object(
  { status: ['status', statusSchema] }
);
