/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProblemDetails {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
  errors?: Record<string, unknown>;
  additionalProperties?: Record<string, unknown>;
}

export const problemDetailsSchema: Schema<ProblemDetails> = typedExpandoObject(
  {
    type: ['type', optional(string())],
    title: ['title', optional(string())],
    status: ['status', optional(number())],
    detail: ['detail', optional(string())],
    instance: ['instance', optional(string())],
    errors: ['errors', optional(dict(unknown()))],
  },
  'additionalProperties',
  optional(unknown())
);
