/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AuthorIdentifiers,
  authorIdentifiersSchema,
} from './authorIdentifiers.js';

export interface PublishedPackage {
  id: string;
  createdOn: string;
  apiEntityId: string;
  packageRepository: string;
  template: string;
  packageName: string;
  version: string;
  additionalDeploymentInformation?: unknown;
  authorIdentifiers: AuthorIdentifiers;
  link: string;
  additionalProperties?: Record<string, unknown>;
}

export const publishedPackageSchema: Schema<PublishedPackage> = lazy(() =>
  typedExpandoObject(
    {
      id: ['id', string()],
      createdOn: ['createdOn', string()],
      apiEntityId: ['apiEntityId', string()],
      packageRepository: ['packageRepository', string()],
      template: ['template', string()],
      packageName: ['packageName', string()],
      version: ['version', string()],
      additionalDeploymentInformation: [
        'additionalDeploymentInformation',
        optional(unknown()),
      ],
      authorIdentifiers: ['authorIdentifiers', authorIdentifiersSchema],
      link: ['link', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
