/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RemovableFeature
 */
export enum RemovableFeature {
  Merging = 'Merging',
  Pagination = 'Pagination',
  Webhooks = 'Webhooks',
  Callbacks = 'Callbacks',
  MultipleAuthSchemes = 'MultipleAuthSchemes',
  Oauth2 = 'OAuth2',
}

/**
 * Schema for RemovableFeature
 */
export const removableFeatureSchema: Schema<RemovableFeature> = stringEnum(
  RemovableFeature
);
