/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, unknown } from '../schema.js';
import { Status, statusSchema } from './status.js';

export interface SdkGenerationStatusResponse {
  status: Status;
  errors?: Record<string, unknown>;
}

export const sdkGenerationStatusResponseSchema: Schema<SdkGenerationStatusResponse> = object(
  {
    status: ['status', statusSchema],
    errors: ['errors', optional(dict(unknown()))],
  }
);
