/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Links, linksSchema } from './links.js';

export interface SdkGenerationAsyncResponse {
  id: string;
  links: Links;
}

export const sdkGenerationAsyncResponseSchema: Schema<SdkGenerationAsyncResponse> = lazy(
  () => object({ id: ['id', string()], links: ['links', linksSchema] })
);
