/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SdkLanguages
 */
export enum SdkLanguages {
  Csharp = 'csharp',
  Java = 'java',
  Php = 'php',
  Python = 'python',
  Ruby = 'ruby',
  Typescript = 'typescript',
  Go = 'go',
}

/**
 * Schema for SdkLanguages
 */
export const sdkLanguagesSchema: Schema<SdkLanguages> = stringEnum(
  SdkLanguages
);
