/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** This structure encapsulates content that goes into a Guides Section. */
export interface SectionItem {
  /** Guide Heading */
  heading: string;
  /** Guide Body Content */
  body: string;
}

export const sectionItemSchema: Schema<SectionItem> = object({
  heading: ['heading', string()],
  body: ['body', string()],
});
