/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StabilityLevelTag
 */
export enum StabilityLevelTag {
  Beta = 'beta',
  Stable = 'stable',
}

/**
 * Schema for StabilityLevelTag
 */
export const stabilityLevelTagSchema: Schema<StabilityLevelTag> = stringEnum(
  StabilityLevelTag
);
