/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  Csnetstandardlib,
  csnetstandardlibSchema,
} from './csnetstandardlib.js';

/** This structure encapsulates all package deployment details. */
export interface TemplatesPackageDeploymentInformation {
  /** This structure contains all details that goes into package deployment. */
  csNetStandardLib: Csnetstandardlib;
  additionalProperties?: Record<string, unknown>;
}

export const templatesPackageDeploymentInformationSchema: Schema<TemplatesPackageDeploymentInformation> = lazy(
  () =>
    typedExpandoObject(
      { csNetStandardLib: ['CS_NET_STANDARD_LIB', csnetstandardlibSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
