/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { ExportFormats, exportFormatsSchema } from './exportFormats';

/** This structure puts together the URL of the file to be transformed, along with the desired export format. */
export interface TransformViaUrlRequest {
  /** The URL for the API specification file.<br><br>**Note:** This URL should be publicly accessible. */
  url: string;
  /** The desired API specification format for the transformation. <br>The format can be any of the [supported formats](https://docs.apimatic.io/api-transformer/overview-transformer#supported-input-formats). */
  exportFormat: ExportFormats;
}

export const transformViaUrlRequestSchema: Schema<TransformViaUrlRequest> = object(
  {
    url: ['url', string()],
    exportFormat: ['export_format', exportFormatsSchema],
  }
);
