/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  UpdateTemplatesPackageDeploymentInformation,
  updateTemplatesPackageDeploymentInformationSchema,
} from './updateTemplatesPackageDeploymentInformation.js';

/** This structure is used to update package deployment details. */
export interface UpdatePackageDeploymentInformation {
  /** This structure helps update package deployment details. */
  templatesPackageDeploymentInformation: UpdateTemplatesPackageDeploymentInformation;
  additionalProperties?: Record<string, unknown>;
}

export const updatePackageDeploymentInformationSchema: Schema<UpdatePackageDeploymentInformation> = lazy(
  () =>
    typedExpandoObject(
      {
        templatesPackageDeploymentInformation: [
          'templatesPackageDeploymentInformation',
          updateTemplatesPackageDeploymentInformationSchema,
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
