/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { Platforms, platformsSchema } from './platforms';

export interface UrlCodeGenerationInput {
  url: string;
  /** The structure contains platforms that APIMatic CodeGen can generate SDKs and Docs in. */
  template: Platforms;
}

export const urlCodeGenerationInputSchema: Schema<UrlCodeGenerationInput> = object(
  { url: ['url', string()], template: ['template', platformsSchema] }
);
