/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { ExportFormats, exportFormatsSchema } from './exportFormats';

/** This structure puts together the URL of the file to be transformed, along with the desired export format. */
export interface UrlTransformationInput {
  /** API Specification URL address */
  url: string;
  /** The structure contains API specification formats that Transformer can convert to. */
  exportFormat: ExportFormats;
}

export const urlTransformationInputSchema: Schema<UrlTransformationInput> = object(
  {
    url: ['url', string()],
    exportFormat: ['export_format', exportFormatsSchema],
  }
);
