/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { CodeGeneration } from './codeGeneration';

/** The Code Generation structure encapsulates all the  the details of an SDK generation performed by a user. */
export interface UserCodeGeneration extends CodeGeneration {
  /** Unique User Identifier */
  userId: string;
  /** API Specification file in a supported format */
  inputFile: string;
}

export const userCodeGenerationSchema: Schema<UserCodeGeneration> = object({
  userId: ['userId', string()],
  inputFile: ['inputFile', string()],
});
