/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ValidationEntry, validationEntrySchema } from './validationEntry.js';

export interface ValidationSummary {
  isSuccess: boolean;
  blocking: ValidationEntry[];
  errors: ValidationEntry[];
  warnings: ValidationEntry[];
  information: ValidationEntry[];
  additionalProperties?: Record<string, unknown>;
}

export const validationSummarySchema: Schema<ValidationSummary> = typedExpandoObject(
  {
    isSuccess: ['isSuccess', boolean()],
    blocking: ['blocking', array(lazy(() => validationEntrySchema))],
    errors: ['errors', array(lazy(() => validationEntrySchema))],
    warnings: ['warnings', array(lazy(() => validationEntrySchema))],
    information: ['information', array(lazy(() => validationEntrySchema))],
  },
  'additionalProperties',
  optional(unknown())
);
