/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dict,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { LineInfo, lineInfoSchema } from './lineInfo.js';

export interface ValidationEntry {
  message: string;
  lineInfo?: LineInfo;
  jsonReferencePath?: string;
  fileReference?: string;
  metadata?: Record<string, string>;
  ruleDocumentationReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const validationEntrySchema: Schema<ValidationEntry> = typedExpandoObject(
  {
    message: ['message', string()],
    lineInfo: ['lineInfo', optional(lazy(() => lineInfoSchema))],
    jsonReferencePath: ['jsonReferencePath', optional(string())],
    fileReference: ['fileReference', optional(string())],
    metadata: ['metadata', optional(dict(string()))],
    ruleDocumentationReference: [
      'ruleDocumentationReference',
      optional(string()),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
