/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ValidationSummary,
  validationSummarySchema,
} from './validationSummary.js';

export interface ValidateApiResult {
  validation: ValidationSummary;
  linting: ValidationSummary;
  additionalProperties?: Record<string, unknown>;
}

export const validateApiResultSchema: Schema<ValidateApiResult> = lazy(() =>
  typedExpandoObject(
    {
      validation: ['validation', validationSummarySchema],
      linting: ['linting', validationSummarySchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
