/**
 * Apimatic APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ValidationEntry, validationEntrySchema } from './validationEntry.js';

export interface ValidationSummary {
  isSuccess: boolean;
  blocking: ValidationEntry[];
  errors: ValidationEntry[];
  warnings: ValidationEntry[];
  information: ValidationEntry[];
  additionalProperties?: Record<string, unknown>;
}

export const validationSummarySchema: Schema<ValidationSummary> = lazy(() =>
  typedExpandoObject(
    {
      isSuccess: ['isSuccess', boolean()],
      blocking: ['blocking', array(validationEntrySchema)],
      errors: ['errors', array(validationEntrySchema)],
      warnings: ['warnings', array(validationEntrySchema)],
      information: ['information', array(validationEntrySchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
