name: Release

on:
  workflow_dispatch:
  push:
    branches: [alpha]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '13', '14']
    name: Release with Node version ${{ matrix.node }}
    steps:
      - name: setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        working-directory: sdk
        run: |
          npm install
          npm install --save-dev @semantic-release/changelog @semantic-release/git
      - name: Check Build
        working-directory: sdk
        run: npm run build
